//
//  Langage.swift
//  CV
//
//  Created by Zappy on 28/08/2023.
//

import SwiftUI

struct Langage: View {
    var body: some View {
        HStack(){
            Text("Langage Informatique")
                .font(.title3)
                .fontWeight(.semibold)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                .padding([.top, .bottom, .trailing])
            
            
            Image(systemName: "laptopcomputer.and.iphone")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
            
            
        }
        
        
        VStack(alignment: .leading){
            HStack{
                Text("Swift")
                    .font(.title3)
                    .fontWeight(.thin)
                    .padding(.bottom,1)
                Spacer()
                Image(systemName: "star.fill")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                
                Image(systemName: "star.fill")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                Image(systemName: "star.fill")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                Image(systemName: "star")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                Image(systemName: "star")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                Image(systemName: "star")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                
            }
            .padding(.horizontal, 50.0)
            
            HStack{
                Text("SwiftUI")
                    .font(.title3)
                    .fontWeight(.thin)
                    .padding(.bottom,1)
                Spacer()
                Image(systemName: "star.fill")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                
                Image(systemName: "star.fill")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                Image(systemName: "star.fill")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                Image(systemName: "star")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                Image(systemName: "star")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                Image(systemName: "star")
                    .resizable(resizingMode: .stretch)
                    .aspectRatio(contentMode: .fill)
                    .padding(.horizontal)
                    .frame(width: 20.0, height: 20.0)
                    .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
                
            }
            .padding(.horizontal, 50.0)
            
        }
        HStack{
            Text("Javascript")
                .font(.title3)
                .fontWeight(.thin)
                .padding(.bottom,1)
            Spacer()
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
        }
        .padding(.horizontal, 50.0)
    
    
        HStack{
            Text("React")
                .font(.title3)
                .fontWeight(.thin)
                .padding(.bottom,1)
            Spacer()
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
        }
        .padding(.horizontal, 50.0)
        
        HStack{
            Text("HTML/CSS")
                .font(.title3)
                .fontWeight(.thin)
                .padding(.bottom,1)
            Spacer()
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
        }
        .padding(.horizontal, 50.0)
        
        HStack{
            Text("Node.JS")
                .font(.title3)
                .fontWeight(.thin)
                .padding(.bottom,1)
            Spacer()
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
        }
        .padding(.horizontal, 50.0)
        
        HStack{
            Text("Mongo DB")
                .font(.title3)
                .fontWeight(.thin)
                .padding(.bottom,1)
            Spacer()
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star.fill")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            Image(systemName: "star")
                .resizable(resizingMode: .stretch)
                .aspectRatio(contentMode: .fill)
                .padding(.horizontal)
                .frame(width: 20.0, height: 20.0)
                .foregroundColor(Color(hue: 0.488, saturation: 0.037, brightness: 0.352))
            
        }
        .padding(.horizontal, 50.0)
 
    }
    
}

#Preview {
    Langage()
}
